openapi: 3.0.3
info:
  title: Auth & Books API
  version: 1.0.0
  description: Authentication and Book management API

servers:
  - url: http://localhost:8080

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    LoginRequest:
      type: object
      properties:
        provider:
          type: string
          example: internal
        params:
          type: object
          additionalProperties: true
      required: [provider, params]

    RegisterRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required: [username, password]

    RefreshRequest:
      type: object
      properties:
        refresh_token:
          type: string
      required: [refresh_token]

    Book:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        author:
          type: string
      required: [id, title, author]

paths:
  /api/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
            example:
              username: alice
              password: alice123
      responses:
        '200':
          description: User registered

  /api/login:
    post:
      summary: Login (internal or external provider)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
            examples:
              internal-admin:
                summary: Internal login (admin)
                value:
                  provider: internal
                  params:
                    username: admin@gmail.com
                    password: p@$$w0rd1
              internal-user:
                summary: Internal login (user)
                value:
                  provider: internal
                  params:
                    username: alice
                    password: alice123
              google-auth:
                summary: Google login
                value:
                  provider: google
                  params:
                    id_token: "1234"
      responses:
        '200':
          description: Login successful

  /api/logout:
    post:
      summary: Logout
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshRequest'
            example:
              refresh_token: CxgvRcOzRgAYcFy6_y6zZtA1DtXdp1DM_4f4gtdFEs4
      responses:
        '200':
          description: Logged out

  /api/refresh:
    post:
      summary: Refresh access token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshRequest'
            example:
              refresh_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
      responses:
        '200':
          description: Token refreshed

  /api/books:
    post:
      security:
        - BearerAuth: [ ]
      summary: Create a book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
            example:
              id: 2
              title: Book B
              author: FrankestienC
      responses:
        '201':
          description: Book created

  /api/books/{id}:
    put:
      security:
        - BearerAuth: [ ]
      summary: Update book by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
            example:
              id: 2
              title: Book B
              author: Frankestien
      responses:
        '200':
          description: Book updated
    delete:
      security:
        - BearerAuth: []
      summary: Delete book
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Book deleted

  /admin/keys/rotate:
    post:
      security:
        - BearerAuth: []
      summary: Rotate signing keys (admin)
      responses:
        '200':
          description: Keys rotated
